{% set version = "16.0.0" %}
{% set name = "azure-mgmt-resource" %}
  {% set version = "15.0.0" %}
{% set sha256 = "0bdbdc9c1ed2ef975d8dff45f358d1e06dc6761eace5b6817f13993447e48a68" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - azure-common >=1.1,<2.0.0
    - azure-mgmt-core >=1.2.0,<2.0.0
    - msrest >=0.5.0

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.resource
  commands:
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Resource Management Client Library for Python

extra:
  recipe-maintainers:
    - Maxyme
    - dhirschfeld
