{% set name = "azure-mgmt-resource" %}
{% set version = "24.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: cf6b8995fcdd407ac9ff1dd474087129429a1d90dbb1ac77f97c19b96237b265

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - isodate>=0.6.1
    - typing-extensions >=4.6.0
    - azure-common >=1.1
    - azure-mgmt-core >=1.5.0

test:
  imports:
    - azure.mgmt.resource
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/resources/azure-mgmt-resource
  summary: Microsoft Azure Resource Management Client Library for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: Microsoft Azure Resource Management Client Library for Python
  dev_url: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/resources/azure-mgmt-resource
  doc_url: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/resources/azure-mgmt-resource

extra:
  recipe-maintainers:
    - Maxyme
    - dhirschfeld
