travis:
  secure:
    BINSTAR_TOKEN: YFypuPYT50SLo2ygaucouuuuH39iVk4qY3VrMHQWWX7G3HIdFltAuwnZnbCQ8Tq2CtgB5/UDfIS/JmdQvxOJxXsyg0ECW+Jq0YFbveYdBg4GNxOKQAHS1a4Pt9iXP7KxWWvl3ZhWTlj12iiqmLpM0TQqjTeyL6vdf5TYdAJ7pMY1NO/68ooTB/NFWoCvFbD9Tfm5ixaEkIFk8dfGOlHhbra2h64h7++x/EpZhMgYfyLkD0JT0GaCwZp4iO5x5Piuug8ag6ZjpCKieDfGInSOuW1clkkFX+EH7cHb6UB0yMvmzDhhPAzCWpBJDJZOxeBAIG1cKJ4pSu8tG0TdHqMBPLt4cNNxR+gdxQcUt4oeb/LuUPJTEZmHKne50NDVWvH0VhimHvlAe4Pu/gEhxWGaHLidPlqT2xYptTEz6bVLmbl1txZ8bc/6jb93Nylz1YFLYUUCUlbKRnzKAxb43R6c1/4B6dIARkb8n3t4Pe8HFhh/2otMdOqdhiNtk98/mVir/Ra5AnrfvMAKXWCFTjfgtzaJ01Q3KLJVw6vEf7JeTi2BdMhOx25vufc5+858fYaixj+U+V6u/hjSDC23fH4MeJ2H7PeHNFHCBs4Q4HujOLF3J6BIqQ0jwmZCFtl6ePjM3MLe8+LR78ElVL/OAwXV2ZHmybVmTHIcYpvsLYCcmuQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
