travis:
  secure:
    BINSTAR_TOKEN: rmwm0Mt6zEu8+a7lH8KaTOw00Tgl9TqykozREH7dtyuvdHyNChJ5xWDhpIm/FQCLk+yoLDKXrEe6ZYlIUEo/UOCEwerdoRpaF3KR62FvR65am7O75P4d+M+NXw+L4AQCh05T2FMFbCvJAgBJWN+l9bzNa09BZT4QFV5VnbzoVUgFabdWfXGMIucMjt+Us9/TfrfsfZi6VP+qel2jpnaagAXjDP+UIFuR65/H7OzsFa/gyYGdambbLO92UKAoagOWaausoi2tKL82g7X3NLhOz4fW9M5FiraGo4kljQEa5kVWUQgCdGHTqxIkCtwr+XLCvqAayoXgsVaKPjVpBSrJJzEOupgl78tzVGWfY2McF1XXM95CRUz/I3B1fdZlFUKVNPjTD2rzYXHPmcwRWdtwuxcCdREtCVz4C6g6ERfs4RRnDuSL2sTQFqkhpkWWVXrSN85+xi8akMWD03eMgMCnKgSuzKdZHg+9cN2NCQHwYWK08ToTfpETN4LmQnsMf5qnyTfNOJTKkkLCYX5Z5xXZM+ItBnd/qLIG/RcnU0MFzQAMiQoz9Ub3ZHt9o+gVKkQOOoU0o2F/2mFJD1eNhG1J/zWhMwxpCNCjewsajEGg5Do8oTb8huUXf1mUj2MRsePevs9723L/cA1vE/cruMzPGjAUf/pjRs1XV+FdyUD69+w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
