travis:
  secure:
    BINSTAR_TOKEN: P7Nj8YH2tT1h5wBYt/pxm0VGz6BESKSZWz+35p1dhrNLrKIWQQMvg0ElK/m/o/z/B3s+IMgqlmEbHMzhSMe3v9ixBnto790ZJFIOxph7lLB8U5vIeRqTlLiuvvYAwTfTB1M9WZEwu8QawUPQa6AmAevJNgGJTcar5aRgaVquBcL+jISK1edc1o/cy7u3llHkdPYf+isqmvjGx1FJFrNxK2l2IWDLerD/3KE8Sh9DoCrh1VVWPVuC7CUtIJkI26Plvz+4AjOf50IDe5mkL8cpg/ms6P/5GhzGZFz7U9W6Iq1EpnB1zhgZrthc6WfADyk+H7gpMofoYVT337ohKreuPofiPIeMi+b7JkSfuommfUYXpnXPuWAbKAxSCxOVByOuJPHrpLba6+C5+AXzTGsrgRZBLkB9y8hHV5/i8Qg+73+dEJczJheA+OtZQBJBymqDcLLLkTMxmJI5GFfEcuPnqnZpA7hdCwK66Gd0VxhQwpbl7YqRkZGcZ8VzJonQqzkRX0Jw2e/VK/OwfFXxYn6Dqe4SjcSf2pRal/bmK1jb16oc9c3uGVBP2Ehp9XlsbReQuCGvTBhRUUcFqMoDdFQ1lt4+yRePhF6VyxDYrLXHIotOWpAOkyIckL2tUpI/JsarvnUCwtIN8MMobLNzDnIcOvan61HeF5qAguKULihL/DU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
